### ISSUE TITLE
Don't install/enable DAV

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/Virtualmin-Config#10]
In the interest of simplifying the UI and user experience, we should remove DAV from the default installation. It doesn't work in a useful way for virtual hosting, anyway (permissions are dangerous and unfixable).

I'm opening the ticket here, but it'll take at least changes in a few places:

1. Apache.pm needs config for DAV removed and disabled or whatever needs to happen to make it not give errors or warnings about DAV not being available (or anything that can possibly be interpreted as an error because if it says "disabled because it is not installed" in the config check we will immediately have people asking how to fix it.
2. Remove virtualmin-dav module dependency from yum-groups and metapackages.
3. May need Virtualmin changes, but probably not, if the dav module isn't installed.

**Comment by iliaross** [comment]
Okay, done. Thanks for your suggestion, Joe!
