### ISSUE TITLE
SASL FLAGS appends '-r' value over and over again

### ISSUE THREAD

**Issue by nicutor** [virtualmin/Virtualmin-Config#3]
Hi,

Each time virtualmin-config-system runs, a new '-r' option is added on /etc/sysconfig/saslauthd:
```
FLAGS="-r -r -r"
```
Can you please check if -r already exists there and add only if not?

I can understand this is not very important, but the issue it may help to improve virtualmin scripts overall.

Thank you.

**Comment by swelljoe** [comment]
Fixed by https://github.com/virtualmin/Virtualmin-Config/commit/f0fd1195c48e7a65cd9b0132bd34c418072d3e40

Thanks for the report.
