### ISSUE TITLE
/etc/resolv.conf nameserver 127.0.0.1 is appended over and over again

### ISSUE THREAD

**Issue by nicutor** [virtualmin/Virtualmin-Config#4]
Another small improvement should be if you can check that
```
nameserver 127.0.0.1
```
already exists on /etc/resolv.conf before added it when virtualmin-config-system runs.

**Comment by swelljoe** [comment]
Resolved by https://github.com/virtualmin/Virtualmin-Config/commit/c0d1116a028cc52a5133a39bce1b53bd3b3b9fde

Thanks for the heads up.
